# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: davidka

steps:
- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'adoption Artifactory'
    targetResolveReleaseRepo: 'pepsico-libs-release'
    targetResolveSnapshotRepo: 'pepsico-libs-snapshot'
    artifactoryDeployService: 'adoption Artifactory'
    targetDeployReleaseRepo: 'pepsico-libs-release'
    targetDeploySnapshotRepo: 'pepsico-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
